plugins {
  id 'com.diffplug.spotless'
  id 'jacoco'
}

dependencies {
  testImplementation(project ":cogni.app")

  def logbackVersion = "1.5.24"
  testImplementation "ch.qos.logback:logback-core:${logbackVersion}"
  testImplementation "ch.qos.logback:logback-classic:${logbackVersion}"

  testImplementation "org.mockito:mockito-core:5.2.0"

  def junitVersion = "5.8.1"
  testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
  testImplementation "org.junit.jupiter:junit-jupiter-params:${junitVersion}"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"
  testRuntimeOnly "org.junit.platform:junit-platform-commons:1.7.0"
}

jacoco {
  toolVersion = "0.8.14"
}

test {
  useJUnitPlatform()
  finalizedBy jacocoTestReport, jacocoTestCoverageVerification

  testLogging {
    events "started", "failed"
  }
}

jacocoTestReport {
  // generate only HTML report
  reports {
    xml.required = false
    csv.required = false
    html.required = true
  }
  sourceDirectories.from = project(':cogni.app').sourceSets.main.java.srcDirs
  classDirectories.from = project(':cogni.app').sourceSets.main.java.classesDirectory
}

jacocoTestCoverageVerification {
  sourceDirectories.from = project(':cogni.app').sourceSets.main.java.srcDirs
  classDirectories.from = project(':cogni.app').sourceSets.main.java.classesDirectory
  afterEvaluate {
    classDirectories.setFrom(files(classDirectories.files.collect {
      fileTree(dir: it, exclude:  [
        // none
      ])
    }))
  }
  violationRules {
    rule {
      enabled = true
      element = 'PACKAGE'
      limit {
        counter = 'LINE'
        value = 'COVEREDRATIO'
        minimum = 0.0
      }
    }
  }
}

// run spotless and format code before the build
classes.dependsOn spotlessApply
