debug=
debugLogPath=/tmp/sl.log
chatModelName=nemotron-3-nano:4b
#chatModelName=ministral-3:8b
#chatModelName=llama3.1:8b

action=startAgent
systemPromptPath=AGENTS.md
chatSessionPath=chat.org
chatLogPath=chatLog.md
streamingDisabled=true
timeoutInSecs=600
tools=currentDateTime
mcpJsonPath=mcp.yaml
